---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it.
name: "logistic_network"

#
# Describe what the target network is/does.
#
description: "logistic network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# list of participating organizations in this network
#
organizations:
  Oem:
    mspid: OemMSP
    peers:
      - peer1.oem.com

  Dealer:
    mspid: DealerMSP
    peers:
      - peer1.dealer.com

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  logisticschannel:
    # List of orderers designated by the application to use for transactions on this channel. 
    orderers:
      - orderer.oem.com

    # Required. list of peers from participating orgs
    peers:
      # Acme peer - with roles played by the peer
      peer1.oem.com:
        # Roles for which this peer may be used
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      # Budget peer - with roles played by the peer
      peer1.dealer.com:
        # Roles for which this peer may be used
        endorsingPeer: true  # SDK will NOT send request for endorsements to this peer
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true    # SDK will NOT allow event subscribers for this peer



      
#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. 
#
orderers:
  orderer.oem.com:
    url: grpc://orderer.oem.com:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    # grpcOptions:
    #   ssl-target-name-override: orderer.oem.com

    # In dev environment the Orderer is NOT enabled for TLS
    # tlsCACerts:
    #   path: comercial-paper/organization/magnetocorp/orderer/orderer.magnetocorp.com/tlscacerts/example.com-cert.pem

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer1.oem.com:

    url: grpc://peer1.oem.com:7051

    # grpcOptions:
    #  ssl-target-name-override: peer1.oem.com

    # tlsCACerts:
    #   path: [ This need to be set if TLS is enabled on peer]

  peer1.dealer.com:

    url: grpc://localhost:8051

    # grpcOptions:
    #  ssl-target-name-override: peer1.dealer.com

  #   # tlsCACerts:
  #   #   path: [ This need to be set if TLS is enabled on peer]

